### ISSUE TITLE
Introduce `visit_span` on `VisitMut` and `Visit`

### ISSUE THREAD

**Issue by hyf0** [oxc-project/backlog#112]
Rolldown currently uses `Span`s as the way to identifier ast nodes. But it would become a problem, if the ast contains duplicate `Span`s.

So

> we could have a new ast pass the will fill up empty span and ensure the uniqueness. 
> https://github.com/rolldown/rolldown/pull/1899#issuecomment-2274936578

I want to ensure the uniqueness of `Span` of every node. So far if I want to do that with the `VisitMut`, I have to enumerate ever node. But with `visit_span`, it would be pretty easy.

**Comment by overlookmotel** [comment]
We'd need to make sure adding `visit_span` doesn't degrade performance. It'll be called for every single AST node, and most visitors don't need it. Hopefully the compiler will be smart enough to inline no-op `visit_span` calls and remove them entirely, but we need to make sure.

Also, for the Rolldown use case, I also imagine using `visit_span` will be pretty expensive. If you know only certain AST node types can have empty/non-unique spans, it's likely to be much faster to do the checks in `visit_module_declaration` (as you're doing now in https://github.com/rolldown/rolldown/pull/1927) and avoid the uniqueness check on every single other node.

**Comment by Boshen** [comment]
> This issue is being transferred. Timeline may not be complete until it finishes.

I broke github :-/ This issue is still in the main repo https://github.com/oxc-project/oxc/issues/4799
