### ISSUE TITLE
Utility to reduce hand written ast construction

### ISSUE THREAD

**Issue by Boshen** [oxc-project/backlog#57]
* https://github.com/rolldown/rolldown/blob/2794b92e75f02a3411af68cb84014b64ff1e3d9f/crates/rolldown_oxc_utils/src/quote/mod.rs
* https://github.com/rolldown/rolldown/blob/main/crates/rolldown_oxc_utils/src/ast_snippet.rs
* https://github.com/swc-project/swc/blob/main/crates/swc_ecma_quote/src/lib.rs
* https://github.com/swc-project/swc/tree/main/crates/swc_ecma_quote_macros

Need some kind of templating to reduce boilerplate and speed up development.

**Comment by Dunqing** [comment]
Seems related to https://github.com/oxc-project/backlog/issues/184
