### ISSUE TITLE
Optimize JSDoc comment processing in `oxc_semantic`

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/backlog#61]
[oxc#4140](https://github.com/oxc-project/oxc/pull/4140) massively speeded up handling JSDoc comments in semantic.

I think it could be sped up further by:

Instead of starting each search starting from a span `previous_span_end`, use the previous index of `SortedComments`, to avoid searching for the index which we already know. I think some of the other code could then be shortened too.

This won't have the dramatic effect that [oxc#4140](https://github.com/oxc-project/oxc/pull/4140) had (!) but might give us 1% speed-up or something.

**Comment by Boshen** [comment]
This is no longer relevant, comment attachment is now done in the parser.
