### ISSUE TITLE
Rename `oxc_codegen` crate to `oxc_print`

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/backlog#63]
As discussed elsewhere, it's a bit confusing because we now have:

1. `oxc_codegen` which prints JS from an AST
2. Codegens which generate Rust code (e.g. `Visit`)

Additionally, "codegen" is compiler jargon. Many users won't be familiar with compilers, and won't know what it means. "print" is much more obvious.

**Comment by Boshen** [comment]
This is a huge breaking change, involving a lot of work reorganizing everything in the codebase, as well as yanking the exiting crate.

I already did the https://crates.io/crates/oxc_printer -> https://crates.io/crates/oxc_codegen a year a go.

Ast codegen comes after `oxc_codegen`, we should rename that thing instead as its only internal.

**Comment by overlookmotel** [comment]
OK cool. That makes sense.
