### ISSUE TITLE
Record `AstNodeId` for all scopes in `Semantic`

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/backlog#65]
As Dunqing said in https://github.com/oxc-project/oxc/pull/4208#issuecomment-2224244611:

> We should set the node_id for all nodes that have a scope, initially I only needed to use it in functions, so I only set for functions.

**Comment by overlookmotel** [comment]
> However, the current scope is conditional, which means that it might not always be possible to find the corresponding node using its scope. This can be a bit confusing.

But after #4248, won't it be the case that every scope has a node ID? So there's only no node ID for scopes which don't exist. If it doesn't exist, in what circumstances would you need to get node for it?

**Comment by Dunqing** [comment]
> But after [#4248](https://github.com/oxc-project/oxc/pull/4248), won't it be the case that every scope has a node ID? 

Yes 

> So there's only no node ID for scopes which don't exist. And if it doesn't exist, in what circumstances would you need to get node for it?

I don't currently need this kind of use.
