### ISSUE TITLE
Inline AST builders

### ISSUE THREAD

**Issue by overlookmotel** [oxc-project/backlog#7]
Add `#[inline]` to all AST builders.

This may increase likelihood that compiler sees it can construct AST node directly in the arena, rather than constructing on stack and then copying into arena.

Could also see if [`Bump::alloc_with`](https://docs.rs/bumpalo/latest/bumpalo/struct.Bump.html#method.alloc_with) helps with this.

AST builders are almost all very minimal, so inlining is unlikely to lead to code bloat. It might actually reduce it.

**Comment by Boshen** [comment]
I suppose we can experiment with this once ast codegen is done.
